# Generated by Django 2.1.2 on 2018-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование организации')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('date_work', models.CharField(max_length=50, verbose_name='Период работы')),
                ('responsibility', models.TextField(verbose_name='Обязанности')),
            ],
        ),
    ]
